bin/cake bake all subjects -f
bin/cake bake all degrees -f
bin/cake bake all sessions -f
bin/cake bake all keywords -f
bin/cake bake all teachers -f
bin/cake bake all users -f
bin/cake bake all degrees_subjects -f
bin/cake bake all keywords_sessions -f
bin/cake bake all subjects_subjects -f
bin/cake bake all subjects_teachers -f